p = '/Users/guo/Documents/solo/demo-Solo/tasks/auto16/backend/server.ts'
L = []
def a(s=''):
    L.append(s)
def w(f,v):
    a(f'  {f}: {v},')
a("import express, { Request, Response } from 'express';")
a("import cors from 'cors';")
a("import { v4 as uuidv4 } from 'uuid';")
a()
a('const app = express();')
a('const PORT = 3001;')
a()
a('app.use(cors());')
a('app.use(express.json());')
a()
a("type TaskStatus = 'todo' | 'in_progress' | 'review' | 'done';")
a("type Priority = 'urgent' | 'high' | 'medium' | 'low';")
a("type ReviewStatus = 'pending' | 'approved' | 'changes_requested';")
a()
for n,fs in [('User',['id: string','username: string','email: string','password: string','avatar?: string','role?: string']),('Task',['id: string','title: string','description: string','status: TaskStatus','priority: Priority','assigneeId: string','createdAt: string','updatedAt: string','dueDate?: string','completedAt?: string']),('Comment',['id: string','taskId: string','userId: string','content: string','createdAt: string']),('Review',['id: string','taskId: string','authorId: string','status: ReviewStatus','description: string','files: ReviewFile[]','createdAt: string','updatedAt: string']),('ReviewFile',['id: string','name: string','content: string','lineComments: LineComment[]']),('LineComment',['id: string','fileId: string','line: number','content: string','userId: string','createdAt: string','resolved?: boolean'])]:
    a(f'interface {n} {{')
    for f in fs:
        a(f'  {f};')
    a('}')
    a()
a("const users = new Map<string, User>();")
a("const tasks = new Map<string, Task>();")
a("const comments = new Map<string, Comment>();")
a("const reviews = new Map<string, Review>();")
a()
a('const user1Id = uuidv4();')
a('const user2Id = uuidv4();')
a('const user3Id = uuidv4();')
a()
for uid,nm,em,rl in [('user1Id','alice','alice@example.com','developer'),('user2Id','bob','bob@example.com','designer'),('user3Id','charlie','charlie@example.com','manager')]:
    a(f'users.set({uid}, {{')
    a(f'  id: {uid},')
    a(f"  username: '{nm}',")
    a(f"  email: '{em}',")
    a("  password: 'password123',")
    a(f"  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed={nm}',")
    a(f"  role: '{rl}',")
    a('});')
    a()
a('const now = new Date();')
a('const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();')
a('const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();')
a()
a('const task1Id = uuidv4();')
a('const task2Id = uuidv4();')
a('const task3Id = uuidv4();')
a('const task4Id = uuidv4();')
a('const task5Id = uuidv4();')
a()
a("app.post('/api/auth/register', (req: Request, res: Response) => {")
a("  const { username, email, password } = req.body;")
a("  if (!username || !email || !password) {")
a("    res.status(400).json({ error: 'username, email, and password are required' });")
a("    return;")
a("  }")
a("  const existing = [...users.values()].find(")
a("    (u) => u.username === username || u.email === email")
a("  );")
a("  if (existing) {")
a("    res.status(409).json({ error: 'User already exists' });")
a("    return;")
a("  }")
a("  const id = uuidv4();")
a("  const user: User = { id, username, email, password, role: 'developer' };")
a("  users.set(id, user);")
a("  const { password: _, ...safe } = user;")
a("  res.status(201).json({ user: safe, token: `dummy-token-${id}` });")
a("});")
a()
a("app.post('/api/auth/login', (req: Request, res: Response) => {")
a("  const { email, password } = req.body;")
a("  if (!email || !password) {")
a("    res.status(400).json({ error: 'email and password are required' });")
a("    return;")
a("  }")
a("  const user = [...users.values()].find(")
a("    (u) => u.email === email && u.password === password")
a("  );")
a("  if (!user) {")
a("    res.status(401).json({ error: 'Invalid credentials' });")
a("    return;")
a("  }")
a("  const { password: _, ...safe } = user;")
a("  res.json({ user: safe, token: `dummy-token-${user.id}` });")
a("});")
a()
a("app.get('/api/users', (_req: Request, res: Response) => {")
a("  const safe = [...users.values()].map(({ password: _, ...u }) => u);")
a("  res.json(safe);")
a("});")
a()
a("  const task = tasks.get(taskId);")
a("  if (task) {")
a("    task.status = 'review';")
a("    task.updatedAt = nowIso;")
a("  }")
a("  res.status(201).json(review);")
a("});")
a()
a("app.get('/api/reviews/:id', (req: Request, res: Response) => {")
a("  const review = reviews.get(req.params.id);")
a("  if (!review) {")
a("    res.status(404).json({ error: 'Review not found' });")
a("    return;")
a("  }")
a("  res.json(review);")
a("});")
a()
a("app.put('/api/reviews/:id/status', (req: Request, res: Response) => {")
a("  const review = reviews.get(req.params.id);")
a("  if (!review) {")
a("    res.status(404).json({ error: 'Review not found' });")
a("    return;")
a("  }")
a("  const { status } = req.body;")
a("  if (!status || !['approved', 'changes_requested'].includes(status)) {")
a("    res.status(400).json({ error: 'Valid status required (approved, changes_requested)' });")
a("    return;")
a("  }")
a("  review.status = status;")
a("  review.updatedAt = new Date().toISOString();")
a()
a("  const task = tasks.get(review.taskId);")
a("  if (task) {")
a("    task.status = 'review';")
a("    task.updatedAt = new Date().toISOString();")
a("  }")
a()
a("  res.json(review);")
a("});")
a()
a("app.get('/api/stats', (_req: Request, res: Response) => {")
a("  const allTasks = [...tasks.values()];")
a("  const total = allTasks.length;")
a("  const completed = allTasks.filter((t) => t.status === 'done').length;")
a()
a("  const nowDate = new Date();")
a("  const overdue = allTasks.filter(")
a("    (t) =>")
a("      t.status !== 'done' &&")
a("      t.dueDate &&")
a("      new Date(t.dueDate) < nowDate")
a("  ).length;")
a()
a("  const completedTasks = allTasks.filter(")
a("    (t) => t.status === 'done' && t.completedAt && t.createdAt")
a("  );")
a("  const avgCompletionDays =")
a("    completedTasks.length > 0")
a("      ? completedTasks.reduce((sum, t) => {")
a("          const days =")
a("            (new Date(t.completedAt!).getTime() - new Date(t.createdAt).getTime()) /")
a("            86400000;")
a("          return sum + days;")
a("        }, 0) / completedTasks.length")
a("      : 0;")
a()
a("  res.json({")
a("    total,")
a("    completed,")
a("    overdue,")
a("    avgCompletionDays: Math.round(avgCompletionDays * 10) / 10,")
a("    byUser,")
a("    dailyTrend,")
a("  });")
a("});")
a()
a("app.listen(PORT, () => {")
a("  console.log(`Server running on http://localhost:${PORT}`);")
a("});")
a()
with open(p, 'w') as f:
    f.write('\n'.join(L) + '\n')
print(f'Done: {len(L)} lines written')
