import { v4 as uuidv4 } from 'uuid';
import type { User, Recipe, Challenge, Trophy } from './types';

export const users: User[] = [
  {
    id: 'user-1',
    username: '厨房小白',
    password: '123456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chef1',
    bio: '热爱美食，正在学习烹饪的小白一枚~',
  },
  {
    id: 'user-2',
    username: '甜品控小美',
    password: '123456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chef2',
    bio: '甜品是我的命，烘焙是我的爱！',
  },
  {
    id: 'user-3',
    username: '川菜大师',
    password: '123456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chef3',
    bio: '麻辣鲜香，川菜无敌！',
  },
  {
    id: 'user-4',
    username: '健康饮食家',
    password: '123456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chef4',
    bio: '少油少盐，健康美味两不误。',
  },
  {
    id: 'user-5',
    username: '面食爱好者',
    password: '123456',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chef5',
    bio: '一碗好面，胜过千言万语。',
  },
];

const generateImageUrl = (keyword: string, index: number) =>
  `https://picsum.photos/seed/${keyword}${index}/400/300`;

export const recipes: Recipe[] = [
  {
    id: 'recipe-1',
    userId: 'user-1',
    username: '厨房小白',
    title: '番茄炒蛋',
    description: '简单又美味的家常菜，新手必学！',
    ingredients: [
      { name: '番茄', amount: '2个' },
      { name: '鸡蛋', amount: '3个' },
      { name: '葱花', amount: '适量' },
      { name: '盐', amount: '少许' },
      { name: '糖', amount: '1勺' },
    ],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散备用。' },
      { order: 2, description: '热锅凉油，倒入蛋液炒至凝固盛出。' },
      { order: 3, description: '锅中加少许油，放入番茄翻炒出汁。' },
      { order: 4, description: '加入盐和糖调味，倒入炒好的鸡蛋翻炒均匀。' },
      { order: 5, description: '撒上葱花即可出锅。' },
    ],
    imageUrl: generateImageUrl('tomato-egg', 1),
    likes: 128,
    likedBy: ['user-2', 'user-3'],
    createdAt: '2024-01-15',
    isPublic: true,
  },
  {
    id: 'recipe-2',
    userId: 'user-2',
    username: '甜品控小美',
    title: '提拉米苏',
    description: '经典意式甜品，浓郁咖啡香配马斯卡彭奶酪',
    ingredients: [
      { name: '马斯卡彭奶酪', amount: '250g' },
      { name: '手指饼干', amount: '200g' },
      { name: '浓缩咖啡', amount: '200ml' },
      { name: '蛋黄', amount: '3个' },
      { name: '细砂糖', amount: '80g' },
      { name: '可可粉', amount: '适量' },
    ],
    steps: [
      { order: 1, description: '蛋黄加糖打发至颜色变浅。' },
      { order: 2, description: '加入马斯卡彭奶酪搅拌均匀。' },
      { order: 3, description: '手指饼干快速蘸取咖啡，铺一层在容器底部。' },
      { order: 4, description: '倒入一半奶酪糊，再铺一层饼干，倒入剩余奶酪糊。' },
      { order: 5, description: '冷藏4小时以上，食用前筛上可可粉。' },
    ],
    imageUrl: generateImageUrl('tiramisu', 2),
    likes: 256,
    likedBy: ['user-1', 'user-4', 'user-5'],
    createdAt: '2024-02-10',
    isPublic: true,
    challengeId: 'challenge-1',
  },
  {
    id: 'recipe-3',
    userId: 'user-3',
    username: '川菜大师',
    title: '麻婆豆腐',
    description: '麻辣鲜香，正宗川味麻婆豆腐',
    ingredients: [
      { name: '嫩豆腐', amount: '1块' },
      { name: '牛肉末', amount: '100g' },
      { name: '郫县豆瓣酱', amount: '2勺' },
      { name: '花椒粉', amount: '1勺' },
      { name: '蒜末', amount: '适量' },
      { name: '葱花', amount: '适量' },
    ],
    steps: [
      { order: 1, description: '豆腐切小块，用盐水焯一下备用。' },
      { order: 2, description: '热锅下油，炒香牛肉末盛出。' },
      { order: 3, description: '锅中留底油，炒香豆瓣酱和蒜末。' },
      { order: 4, description: '加入适量水烧开，放入豆腐和牛肉末。' },
      { order: 5, description: '勾芡，撒上花椒粉和葱花即可。' },
    ],
    imageUrl: generateImageUrl('mapo-tofu', 3),
    likes: 189,
    likedBy: ['user-1', 'user-2'],
    createdAt: '2024-02-20',
    isPublic: true,
  },
  {
    id: 'recipe-4',
    userId: 'user-4',
    username: '健康饮食家',
    title: '牛油果沙拉',
    description: '清爽健康的牛油果沙拉，减脂好选择',
    ingredients: [
      { name: '牛油果', amount: '1个' },
      { name: '圣女果', amount: '10颗' },
      { name: '生菜', amount: '适量' },
      { name: '橄榄油', amount: '2勺' },
      { name: '柠檬汁', amount: '1勺' },
      { name: '黑胡椒', amount: '少许' },
    ],
    steps: [
      { order: 1, description: '牛油果去核切块，圣女果对半切。' },
      { order: 2, description: '生菜洗净撕成小块。' },
      { order: 3, description: '所有蔬菜放入大碗中。' },
      { order: 4, description: '淋上橄榄油和柠檬汁。' },
      { order: 5, description: '撒上黑胡椒，拌匀即可。' },
    ],
    imageUrl: generateImageUrl('avocado-salad', 4),
    likes: 95,
    likedBy: ['user-5'],
    createdAt: '2024-03-01',
    isPublic: true,
  },
  {
    id: 'recipe-5',
    userId: 'user-5',
    username: '面食爱好者',
    title: '红烧牛肉面',
    description: '香浓汤底，软烂牛肉，一碗满足的牛肉面',
    ingredients: [
      { name: '牛腩', amount: '500g' },
      { name: '面条', amount: '适量' },
      { name: '八角', amount: '2个' },
      { name: '桂皮', amount: '1块' },
      { name: '生抽', amount: '3勺' },
      { name: '老抽', amount: '1勺' },
      { name: '青菜', amount: '适量' },
    ],
    steps: [
      { order: 1, description: '牛腩切块焯水，捞出洗净。' },
      { order: 2, description: '锅中放油，炒香香料，加入牛肉翻炒。' },
      { order: 3, description: '加生抽老抽上色，加水没过牛肉。' },
      { order: 4, description: '大火烧开后转小火炖2小时。' },
      { order: 5, description: '面条煮熟，青菜焯水，浇上牛肉汤即可。' },
    ],
    imageUrl: generateImageUrl('beef-noodle', 5),
    likes: 312,
    likedBy: ['user-1', 'user-2', 'user-3', 'user-4'],
    createdAt: '2024-03-10',
    isPublic: true,
  },
  {
    id: 'recipe-6',
    userId: 'user-1',
    username: '厨房小白',
    title: '蒜蓉西兰花',
    description: '简单快手的健康素菜',
    ingredients: [
      { name: '西兰花', amount: '1颗' },
      { name: '大蒜', amount: '5瓣' },
      { name: '蚝油', amount: '1勺' },
      { name: '盐', amount: '少许' },
    ],
    steps: [
      { order: 1, description: '西兰花切小朵，洗净沥干。' },
      { order: 2, description: '大蒜切末备用。' },
      { order: 3, description: '热锅下油，爆香蒜末。' },
      { order: 4, description: '放入西兰花翻炒，加少许水焖2分钟。' },
      { order: 5, description: '加蚝油和盐调味，翻炒均匀出锅。' },
    ],
    imageUrl: generateImageUrl('broccoli', 6),
    likes: 67,
    likedBy: [],
    createdAt: '2024-03-15',
    isPublic: true,
  },
  {
    id: 'recipe-7',
    userId: 'user-2',
    username: '甜品控小美',
    title: '芒果班戟',
    description: '港式经典甜品，香甜芒果配淡奶油',
    ingredients: [
      { name: '芒果', amount: '2个' },
      { name: '淡奶油', amount: '200ml' },
      { name: '低筋面粉', amount: '80g' },
      { name: '牛奶', amount: '150ml' },
      { name: '鸡蛋', amount: '2个' },
      { name: '糖粉', amount: '30g' },
    ],
    steps: [
      { order: 1, description: '鸡蛋打散，加入牛奶和融化的黄油拌匀。' },
      { order: 2, description: '筛入低筋面粉，搅拌至无颗粒。' },
      { order: 3, description: '平底锅小火，倒入面糊摊成薄饼。' },
      { order: 4, description: '淡奶油加糖打发至硬性发泡。' },
      { order: 5, description: '饼皮中间放奶油和芒果块，包起来即可。' },
    ],
    imageUrl: generateImageUrl('mango-pancake', 7),
    likes: 178,
    likedBy: ['user-1', 'user-5'],
    createdAt: '2024-03-20',
    isPublic: true,
    challengeId: 'challenge-1',
  },
  {
    id: 'recipe-8',
    userId: 'user-3',
    username: '川菜大师',
    title: '水煮肉片',
    description: '麻辣过瘾的经典川菜',
    ingredients: [
      { name: '猪里脊肉', amount: '300g' },
      { name: '豆芽', amount: '200g' },
      { name: '郫县豆瓣酱', amount: '3勺' },
      { name: '干辣椒', amount: '适量' },
      { name: '花椒', amount: '1勺' },
      { name: '蒜末', amount: '适量' },
    ],
    steps: [
      { order: 1, description: '肉片用淀粉、料酒腌制15分钟。' },
      { order: 2, description: '豆芽焯水铺在碗底。' },
      { order: 3, description: '锅中炒香豆瓣酱和蒜末，加水烧开。' },
      { order: 4, description: '肉片逐片放入锅中，煮熟连汤倒入碗中。' },
      { order: 5, description: '表面撒干辣椒和花椒，淋上热油激发香味。' },
    ],
    imageUrl: generateImageUrl('sliced-pork', 8),
    likes: 234,
    likedBy: ['user-5'],
    createdAt: '2024-03-25',
    isPublic: true,
  },
  {
    id: 'recipe-9',
    userId: 'user-4',
    username: '健康饮食家',
    title: '鸡胸肉藜麦沙拉',
    description: '高蛋白低脂肪的健身餐',
    ingredients: [
      { name: '鸡胸肉', amount: '200g' },
      { name: '藜麦', amount: '50g' },
      { name: '黄瓜', amount: '1根' },
      { name: '小番茄', amount: '10颗' },
      { name: '橄榄油', amount: '2勺' },
      { name: '意大利黑醋', amount: '1勺' },
    ],
    steps: [
      { order: 1, description: '藜麦洗净，加水煮15分钟至透明。' },
      { order: 2, description: '鸡胸肉用盐和黑胡椒腌制，煎至两面金黄。' },
      { order: 3, description: '黄瓜切片，小番茄对半切。' },
      { order: 4, description: '所有材料放入大碗中。' },
      { order: 5, description: '淋上橄榄油和黑醋汁，拌匀即可。' },
    ],
    imageUrl: generateImageUrl('quinoa-salad', 9),
    likes: 145,
    likedBy: ['user-2'],
    createdAt: '2024-04-01',
    isPublic: true,
  },
  {
    id: 'recipe-10',
    userId: 'user-5',
    username: '面食爱好者',
    title: '葱油拌面',
    description: '上海经典小吃，葱香四溢',
    ingredients: [
      { name: '细面条', amount: '200g' },
      { name: '小葱', amount: '一把' },
      { name: '生抽', amount: '2勺' },
      { name: '老抽', amount: '1勺' },
      { name: '糖', amount: '1勺' },
      { name: '食用油', amount: '适量' },
    ],
    steps: [
      { order: 1, description: '小葱洗净切段，葱白葱绿分开。' },
      { order: 2, description: '锅中多放油，小火慢慢炸葱白和葱绿至焦黄。' },
      { order: 3, description: '加入生抽、老抽、糖调成酱汁。' },
      { order: 4, description: '面条煮熟，捞出沥干。' },
      { order: 5, description: '浇上葱油酱汁，拌匀即可享用。' },
    ],
    imageUrl: generateImageUrl('scallion-noodles', 10),
    likes: 198,
    likedBy: ['user-1', 'user-3'],
    createdAt: '2024-04-05',
    isPublic: true,
  },
  {
    id: 'recipe-11',
    userId: 'user-1',
    username: '厨房小白',
    title: '蛋炒饭',
    description: '粒粒分明的经典蛋炒饭',
    ingredients: [
      { name: '隔夜米饭', amount: '2碗' },
      { name: '鸡蛋', amount: '2个' },
      { name: '葱花', amount: '适量' },
      { name: '盐', amount: '少许' },
      { name: '生抽', amount: '半勺' },
    ],
    steps: [
      { order: 1, description: '鸡蛋打散，米饭打散备用。' },
      { order: 2, description: '热锅下油，倒入蛋液快速炒散。' },
      { order: 3, description: '倒入米饭，大火翻炒均匀。' },
      { order: 4, description: '加少许盐和生抽调味。' },
      { order: 5, description: '撒上葱花，翻炒均匀出锅。' },
    ],
    imageUrl: generateImageUrl('egg-fried-rice', 11),
    likes: 156,
    likedBy: ['user-5'],
    createdAt: '2024-04-10',
    isPublic: true,
  },
  {
    id: 'recipe-12',
    userId: 'user-2',
    username: '甜品控小美',
    title: '草莓慕斯蛋糕',
    description: '粉嫩少女心的草莓慕斯',
    ingredients: [
      { name: '草莓', amount: '300g' },
      { name: '淡奶油', amount: '200ml' },
      { name: '奶油奶酪', amount: '150g' },
      { name: '吉利丁片', amount: '10g' },
      { name: '细砂糖', amount: '50g' },
      { name: '消化饼干', amount: '100g' },
    ],
    steps: [
      { order: 1, description: '消化饼干压碎，拌入融化的黄油铺底冷藏。' },
      { order: 2, description: '奶油奶酪加糖打发至顺滑。' },
      { order: 3, description: '草莓打成泥，加入泡软的吉利丁片隔水融化。' },
      { order: 4, description: '淡奶油打发至6分发，与奶酪糊和草莓泥混合。' },
      { order: 5, description: '倒入模具中，冷藏4小时以上脱模。' },
    ],
    imageUrl: generateImageUrl('strawberry-mousse', 12),
    likes: 289,
    likedBy: ['user-1', 'user-4', 'user-5'],
    createdAt: '2024-04-15',
    isPublic: true,
    challengeId: 'challenge-1',
  },
  {
    id: 'recipe-13',
    userId: 'user-3',
    username: '川菜大师',
    title: '鱼香肉丝',
    description: '酸甜微辣的经典鱼香味',
    ingredients: [
      { name: '猪里脊肉', amount: '250g' },
      { name: '木耳', amount: '适量' },
      { name: '胡萝卜', amount: '半根' },
      { name: '青椒', amount: '1个' },
      { name: '泡椒', amount: '适量' },
      { name: '醋', amount: '2勺' },
      { name: '糖', amount: '2勺' },
    ],
    steps: [
      { order: 1, description: '猪肉切丝，用淀粉腌制10分钟。' },
      { order: 2, description: '木耳、胡萝卜、青椒切丝备用。' },
      { order: 3, description: '调制鱼香汁：醋、糖、生抽、淀粉、水。' },
      { order: 4, description: '热锅下油，炒香泡椒，滑炒肉丝盛出。' },
      { order: 5, description: '炒香蔬菜丝，倒入肉丝和鱼香汁，翻炒均匀。' },
    ],
    imageUrl: generateImageUrl('fish-fragrant-pork', 13),
    likes: 167,
    likedBy: ['user-1'],
    createdAt: '2024-04-20',
    isPublic: true,
  },
  {
    id: 'recipe-14',
    userId: 'user-4',
    username: '健康饮食家',
    title: '烤蔬菜拼盘',
    description: '低卡美味的烤箱蔬菜',
    ingredients: [
      { name: '南瓜', amount: '200g' },
      { name: '紫薯', amount: '2个' },
      { name: '胡萝卜', amount: '1根' },
      { name: '西兰花', amount: '半颗' },
      { name: '橄榄油', amount: '2勺' },
      { name: '海盐', amount: '少许' },
      { name: '黑胡椒', amount: '少许' },
    ],
    steps: [
      { order: 1, description: '所有蔬菜洗净切块。' },
      { order: 2, description: '淋上橄榄油，撒上海盐和黑胡椒。' },
      { order: 3, description: '翻拌均匀，铺在烤盘上。' },
      { order: 4, description: '烤箱预热200度，烤25分钟。' },
      { order: 5, description: '取出装盘即可享用。' },
    ],
    imageUrl: generateImageUrl('roasted-veggies', 14),
    likes: 89,
    likedBy: [],
    createdAt: '2024-04-25',
    isPublic: true,
  },
  {
    id: 'recipe-15',
    userId: 'user-5',
    username: '面食爱好者',
    title: '意大利肉酱面',
    description: '浓郁番茄肉酱配意面',
    ingredients: [
      { name: '意大利面', amount: '200g' },
      { name: '牛肉末', amount: '200g' },
      { name: '番茄', amount: '3个' },
      { name: '洋葱', amount: '半个' },
      { name: '蒜末', amount: '适量' },
      { name: '番茄酱', amount: '2勺' },
      { name: '罗勒叶', amount: '少许' },
    ],
    steps: [
      { order: 1, description: '番茄去皮切丁，洋葱切丁，蒜切末。' },
      { order: 2, description: '热锅下油，炒香洋葱和蒜末。' },
      { order: 3, description: '加入牛肉末炒散，加番茄丁炒出汁。' },
      { order: 4, description: '加番茄酱和罗勒叶，小火炖30分钟。' },
      { order: 5, description: '意面煮熟，浇上肉酱，撒上芝士粉。' },
    ],
    imageUrl: generateImageUrl('spaghetti-bolognese', 15),
    likes: 245,
    likedBy: ['user-2', 'user-3'],
    createdAt: '2024-05-01',
    isPublic: true,
    challengeId: 'challenge-2',
  },
  {
    id: 'recipe-16',
    userId: 'user-1',
    username: '厨房小白',
    title: '可乐鸡翅',
    description: '甜香软嫩的新手友好菜',
    ingredients: [
      { name: '鸡翅中', amount: '8个' },
      { name: '可乐', amount: '1罐' },
      { name: '生抽', amount: '2勺' },
      { name: '老抽', amount: '1勺' },
      { name: '姜片', amount: '适量' },
      { name: '料酒', amount: '1勺' },
    ],
    steps: [
      { order: 1, description: '鸡翅两面划刀，方便入味。' },
      { order: 2, description: '鸡翅冷水下锅，加料酒和姜片焯水。' },
      { order: 3, description: '锅中放少许油，鸡翅煎至两面金黄。' },
      { order: 4, description: '加入生抽、老抽、可乐，大火烧开。' },
      { order: 5, description: '转小火炖15分钟，大火收汁即可。' },
    ],
    imageUrl: generateImageUrl('cola-chicken', 16),
    likes: 201,
    likedBy: ['user-2', 'user-5'],
    createdAt: '2024-05-05',
    isPublic: true,
  },
  {
    id: 'recipe-17',
    userId: 'user-2',
    username: '甜品控小美',
    title: '抹茶千层蛋糕',
    description: '清新抹茶味的千层蛋糕',
    ingredients: [
      { name: '抹茶粉', amount: '10g' },
      { name: '低筋面粉', amount: '100g' },
      { name: '牛奶', amount: '250ml' },
      { name: '鸡蛋', amount: '2个' },
      { name: '淡奶油', amount: '300ml' },
      { name: '糖粉', amount: '50g' },
    ],
    steps: [
      { order: 1, description: '鸡蛋打散，加入牛奶和融化的黄油。' },
      { order: 2, description: '筛入低筋面粉和抹茶粉，搅拌均匀。' },
      { order: 3, description: '平底锅小火摊成薄饼，约20张。' },
      { order: 4, description: '淡奶油加糖打发至硬性发泡。' },
      { order: 5, description: '一层饼皮一层奶油，叠起来冷藏2小时。' },
    ],
    imageUrl: generateImageUrl('matcha-millecrepe', 17),
    likes: 267,
    likedBy: ['user-1', 'user-4'],
    createdAt: '2024-05-10',
    isPublic: true,
    challengeId: 'challenge-1',
  },
  {
    id: 'recipe-18',
    userId: 'user-3',
    username: '川菜大师',
    title: '宫保鸡丁',
    description: '麻辣鲜香的经典川菜',
    ingredients: [
      { name: '鸡胸肉', amount: '300g' },
      { name: '花生米', amount: '50g' },
      { name: '干辣椒', amount: '适量' },
      { name: '花椒', amount: '1勺' },
      { name: '葱白', amount: '适量' },
      { name: '醋', amount: '1勺' },
      { name: '糖', amount: '1勺' },
    ],
    steps: [
      { order: 1, description: '鸡肉切丁，用淀粉、料酒腌制15分钟。' },
      { order: 2, description: '调制料汁：醋、糖、生抽、淀粉、水。' },
      { order: 3, description: '热锅下油，爆香干辣椒和花椒。' },
      { order: 4, description: '放入鸡丁快速滑炒至变色。' },
      { order: 5, description: '加入料汁和花生米，翻炒均匀出锅。' },
    ],
    imageUrl: generateImageUrl('kung-pao-chicken', 18),
    likes: 178,
    likedBy: ['user-5'],
    createdAt: '2024-05-15',
    isPublic: true,
  },
  {
    id: 'recipe-19',
    userId: 'user-4',
    username: '健康饮食家',
    title: '三文鱼牛油果饭',
    description: '日式健康丼饭',
    ingredients: [
      { name: '三文鱼', amount: '150g' },
      { name: '牛油果', amount: '1个' },
      { name: '米饭', amount: '2碗' },
      { name: '海苔', amount: '适量' },
      { name: '酱油', amount: '2勺' },
      { name: '芥末', amount: '少许' },
    ],
    steps: [
      { order: 1, description: '三文鱼切片，牛油果切片。' },
      { order: 2, description: '米饭盛碗中，稍微压实。' },
      { order: 3, description: '三文鱼和牛油果铺在米饭上。' },
      { order: 4, description: '撒上海苔碎和芝麻。' },
      { order: 5, description: '淋上酱油，挤少许芥末即可。' },
    ],
    imageUrl: generateImageUrl('salmon-avocado', 19),
    likes: 134,
    likedBy: ['user-2'],
    createdAt: '2024-05-20',
    isPublic: true,
  },
  {
    id: 'recipe-20',
    userId: 'user-5',
    username: '面食爱好者',
    title: '武汉热干面',
    description: '地道武汉风味热干面',
    ingredients: [
      { name: '碱水面', amount: '200g' },
      { name: '芝麻酱', amount: '2勺' },
      { name: '萝卜丁', amount: '适量' },
      { name: '酸豆角', amount: '适量' },
      { name: '葱花', amount: '适量' },
      { name: '生抽', amount: '1勺' },
      { name: '辣油', amount: '1勺' },
    ],
    steps: [
      { order: 1, description: '芝麻酱用香油慢慢澥开，调至顺滑。' },
      { order: 2, description: '碱水面煮熟，捞出沥干拌油。' },
      { order: 3, description: '碗中放生抽、盐、少许面汤。' },
      { order: 4, description: '放入面条，浇上芝麻酱。' },
      { order: 5, description: '撒上萝卜丁、酸豆角、葱花，淋辣油拌匀。' },
    ],
    imageUrl: generateImageUrl('hot-dry-noodles', 20),
    likes: 223,
    likedBy: ['user-1', 'user-3'],
    createdAt: '2024-05-25',
    isPublic: true,
    challengeId: 'challenge-2',
  },
];

const now = new Date();
const futureDate3Days = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);
const futureDate5Days = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000);
const pastStartDate = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
const pastEndDate = new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000);

export const challenges: Challenge[] = [
  {
    id: 'challenge-1',
    title: '夏日清爽甜品',
    description: '炎热夏天，来一份清爽解腻的甜品吧！',
    rules: '1. 必须为甜品类菜品\n2. 适合夏季食用，口感清爽\n3. 每人限投一篇作品\n4. 由社区点赞评选获胜者',
    startDate: pastStartDate.toISOString(),
    endDate: futureDate3Days.toISOString(),
    isActive: true,
    participantRecipes: ['recipe-2', 'recipe-7', 'recipe-12', 'recipe-17'],
  },
  {
    id: 'challenge-2',
    title: '最棒的意面',
    description: '展示你的意面制作技艺，争夺意面之王称号！',
    rules: '1. 必须为意大利面类菜品\n2. 可以是任何风味的意面\n3. 每人限投一篇作品\n4. 由社区点赞评选获胜者',
    startDate: pastStartDate.toISOString(),
    endDate: futureDate5Days.toISOString(),
    isActive: true,
    participantRecipes: ['recipe-15', 'recipe-20'],
  },
  {
    id: 'challenge-3',
    title: '家常菜大赛',
    description: '第一届家常菜大赛已经圆满结束！',
    rules: '1. 必须为家常菜品\n2. 食材常见，做法简单\n3. 每人限投一篇作品',
    startDate: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: pastEndDate.toISOString(),
    isActive: false,
    participantRecipes: ['recipe-1', 'recipe-5', 'recipe-11'],
    winners: {
      first: { recipeId: 'recipe-5', userId: 'user-5', username: '面食爱好者' },
      second: { recipeId: 'recipe-1', userId: 'user-1', username: '厨房小白' },
      third: { recipeId: 'recipe-11', userId: 'user-1', username: '厨房小白' },
    },
  },
];

export const trophies: Trophy[] = [
  {
    id: 'trophy-1',
    userId: 'user-5',
    challengeId: 'challenge-3',
    challengeTitle: '家常菜大赛',
    rank: 'first',
    awardedAt: pastEndDate.toISOString(),
  },
  {
    id: 'trophy-2',
    userId: 'user-1',
    challengeId: 'challenge-3',
    challengeTitle: '家常菜大赛',
    rank: 'second',
    awardedAt: pastEndDate.toISOString(),
  },
  {
    id: 'trophy-3',
    userId: 'user-1',
    challengeId: 'challenge-3',
    challengeTitle: '家常菜大赛',
    rank: 'third',
    awardedAt: pastEndDate.toISOString(),
  },
];
